version: '3.8'
services:
  flask-backend:
    build: ./backend/
    restart: always
    volumes:
      - ./backend/app:/app/
    network_mode: host
    command: sh -c "migrations/restore.sh && python3 main.py"
  # react-frontend:
  #   build: ./frontend/
  #   restart: always
  #   network_mode: host