"""Auto migration

Revision ID: 101a58dec372
Revises: 
Create Date: 2020-12-19 16:10:03.106333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101a58dec372'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
