"""Auto migration

Revision ID: 457526d6d0c2
Revises: 
Create Date: 2020-12-06 16:32:33.651515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457526d6d0c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
