"""Auto migration

Revision ID: 478a39e8c98b
Revises: 
Create Date: 2020-12-21 12:21:00.286524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478a39e8c98b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
