"""Auto migration

Revision ID: 489262e5edf6
Revises: 
Create Date: 2020-12-22 16:42:09.041760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489262e5edf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
