"""Auto migration

Revision ID: 788cd64371a7
Revises: 
Create Date: 2020-11-29 08:56:59.088094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788cd64371a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
