import os

PROJECT_NAME = os.getenv("PROJECT_NAME")
API_V1_STR = "/api/v1"

EVIRONMENT = os.getenv('EVIRONMENT')
if EVIRONMENT == 'development':
    DEBUG = True
else: 
    DEBUG == False

ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 2
FRESH_TOKEN_EXPIRE_MINUTES = 60 * 24 * 8    
ENCODE_TYPE = "utf-8"    
ALGORITHM = "HS256"
ROUNDS = 1994
DIGEST = 'sha256'
SALT_SIZE = 16
SALT = bytes(os.environ["SALT"], "utf-8").decode('unicode_escape')
# SALT = os.urandom(SALT_SIZE)

SECRET_KEY = os.getenv("SECRET_KEY")
DATABASE_TYPE = os.getenv("DATABASE_TYPE")
DATABASE_USER = os.getenv("DATABASE_USER")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
DATABASE_HOST = os.getenv("DATABASE_HOST")
DATABASE_NAME = os.getenv("DATABASE_NAME")
SQLALCHEMY_DATABASE_URI = (f"{DATABASE_TYPE}://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}/{DATABASE_NAME}")
       