name: PRODUCTION
on:
  push:
    tags:
    - 'backend-v*.*.*'
    paths:
    - backend/**
    branches:
    - main
  pull_request:
    tags:
    - 'backend-v*.*.*'
    paths:
    - backend/**
    branches:
    - main
env:
  # Variable name
  PROJECT_NAME: film
  BASE_IMAGE: backend


  # dockerhub container
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:

  frontend:
    name: Building image backend
    runs-on: ubuntu-latest
    steps:

    # [Step-1] check config git
    - uses: actions/checkout@v2
              
    # [Step-2] login dockerhub container
    - name: Login to DockerHub Registry
      run: |
        echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
    
    # [Step-3] buid and tag image from Dockerfile
    - name: Build and tag the image
      run: |
        docker build -t $BASE_IMAGE -t $DOCKERHUB_USERNAME/$PROJECT_NAME:$BASE_IMAGE ./backend/
    
    # [Step-4] Push image to docker hub
    - name: Push image to DockerHub
      run: |
        docker push $DOCKERHUB_USERNAME/$PROJECT_NAME:$BASE_IMAGE